Traceback (most recent call last):
  File "/home/varun/miniconda3/envs/cv-as1/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/varun/miniconda3/envs/cv-as1/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/varun/IIIT/SEM6/Computer Vision/assignments/assignment-1-Varun0157/MLP Classification on Image Features/src/q3.py", line 58, in <module>
    main()
  File "/home/varun/IIIT/SEM6/Computer Vision/assignments/assignment-1-Varun0157/MLP Classification on Image Features/src/q3.py", line 34, in main
    train_model(
  File "/home/varun/IIIT/SEM6/Computer Vision/assignments/assignment-1-Varun0157/MLP Classification on Image Features/src/utils/model.py", line 33, in train_model
    train_loader = get_dataloader(os.path.join(data_path, "train.csv"), **args)
  File "/home/varun/IIIT/SEM6/Computer Vision/assignments/assignment-1-Varun0157/MLP Classification on Image Features/src/utils/data.py", line 59, in get_dataloader
    dataset = ImageDataset(csv_file, transform)
  File "/home/varun/IIIT/SEM6/Computer Vision/assignments/assignment-1-Varun0157/MLP Classification on Image Features/src/utils/data.py", line 35, in __init__
    self.data = pd.read_csv(csv_file)
  File "/home/varun/miniconda3/envs/cv-as1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/varun/miniconda3/envs/cv-as1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 626, in _read
    return parser.read(nrows)
  File "/home/varun/miniconda3/envs/cv-as1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
  File "/home/varun/miniconda3/envs/cv-as1/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
  File "parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 905, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2061, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'.
